/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoftMurmurRouteImport } from './routes/soft-murmur'
import { Route as PdfToolsRouteImport } from './routes/pdf-tools'
import { Route as MedicalCertificateRouteImport } from './routes/medical-certificate'
import { Route as FileConvertRouteImport } from './routes/file-convert'
import { Route as DownloaderRouteImport } from './routes/downloader'
import { Route as CerdikaRouteImport } from './routes/cerdika'
import { Route as IndexRouteImport } from './routes/index'

const SoftMurmurRoute = SoftMurmurRouteImport.update({
  id: '/soft-murmur',
  path: '/soft-murmur',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToolsRoute = PdfToolsRouteImport.update({
  id: '/pdf-tools',
  path: '/pdf-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalCertificateRoute = MedicalCertificateRouteImport.update({
  id: '/medical-certificate',
  path: '/medical-certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConvertRoute = FileConvertRouteImport.update({
  id: '/file-convert',
  path: '/file-convert',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloaderRoute = DownloaderRouteImport.update({
  id: '/downloader',
  path: '/downloader',
  getParentRoute: () => rootRouteImport,
} as any)
const CerdikaRoute = CerdikaRouteImport.update({
  id: '/cerdika',
  path: '/cerdika',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cerdika': typeof CerdikaRoute
  '/downloader': typeof DownloaderRoute
  '/file-convert': typeof FileConvertRoute
  '/medical-certificate': typeof MedicalCertificateRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/soft-murmur': typeof SoftMurmurRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cerdika': typeof CerdikaRoute
  '/downloader': typeof DownloaderRoute
  '/file-convert': typeof FileConvertRoute
  '/medical-certificate': typeof MedicalCertificateRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/soft-murmur': typeof SoftMurmurRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cerdika': typeof CerdikaRoute
  '/downloader': typeof DownloaderRoute
  '/file-convert': typeof FileConvertRoute
  '/medical-certificate': typeof MedicalCertificateRoute
  '/pdf-tools': typeof PdfToolsRoute
  '/soft-murmur': typeof SoftMurmurRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cerdika'
    | '/downloader'
    | '/file-convert'
    | '/medical-certificate'
    | '/pdf-tools'
    | '/soft-murmur'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cerdika'
    | '/downloader'
    | '/file-convert'
    | '/medical-certificate'
    | '/pdf-tools'
    | '/soft-murmur'
  id:
    | '__root__'
    | '/'
    | '/cerdika'
    | '/downloader'
    | '/file-convert'
    | '/medical-certificate'
    | '/pdf-tools'
    | '/soft-murmur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CerdikaRoute: typeof CerdikaRoute
  DownloaderRoute: typeof DownloaderRoute
  FileConvertRoute: typeof FileConvertRoute
  MedicalCertificateRoute: typeof MedicalCertificateRoute
  PdfToolsRoute: typeof PdfToolsRoute
  SoftMurmurRoute: typeof SoftMurmurRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soft-murmur': {
      id: '/soft-murmur'
      path: '/soft-murmur'
      fullPath: '/soft-murmur'
      preLoaderRoute: typeof SoftMurmurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-tools': {
      id: '/pdf-tools'
      path: '/pdf-tools'
      fullPath: '/pdf-tools'
      preLoaderRoute: typeof PdfToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-certificate': {
      id: '/medical-certificate'
      path: '/medical-certificate'
      fullPath: '/medical-certificate'
      preLoaderRoute: typeof MedicalCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-convert': {
      id: '/file-convert'
      path: '/file-convert'
      fullPath: '/file-convert'
      preLoaderRoute: typeof FileConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloader': {
      id: '/downloader'
      path: '/downloader'
      fullPath: '/downloader'
      preLoaderRoute: typeof DownloaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerdika': {
      id: '/cerdika'
      path: '/cerdika'
      fullPath: '/cerdika'
      preLoaderRoute: typeof CerdikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CerdikaRoute: CerdikaRoute,
  DownloaderRoute: DownloaderRoute,
  FileConvertRoute: FileConvertRoute,
  MedicalCertificateRoute: MedicalCertificateRoute,
  PdfToolsRoute: PdfToolsRoute,
  SoftMurmurRoute: SoftMurmurRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
